# Generated by Django 4.2.6 on 2023-10-25 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('description', models.TextField(default='')),
                ('repeat', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='never', max_length=10)),
                ('timeStart', models.TimeField()),
                ('timeEnd', models.TimeField(null=True)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField(default=datetime.date(9999, 12, 31))),
                ('dayOfWeek', models.IntegerField(null=True)),
                ('dayOfMonth', models.IntegerField(null=True)),
            ],
        ),
    ]
