# Generated by Django 4.2.6 on 2023-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remind_type',
            field=models.CharField(choices=[('message', 'Message'), ('phone_call', 'Phone Call'), ('wechat', 'WeChat')], default='wechat', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder',
            field=models.TimeField(null=True),
        ),
    ]
