# Generated by Django 4.2.7 on 2023-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wechat_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('messages', models.BinaryField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
