# Generated by Django 4.2.6 on 2023-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wechat_id', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('temp_token', models.CharField(max_length=100, null=True, unique=True)),
                ('temp_token_expires', models.DateTimeField(null=True)),
            ],
        ),
    ]
